behaviors:
  ThrowCatch:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 18432
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 1
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 5e6
    time_horizon: 100
    summary_freq: 5000
    threaded: true